pcap-dnsproxy: v0.4.6.2

diff --git a/package/external/chengr28/pcap-dnsproxy/files/pcap-dnsproxy.init b/package/external/chengr28/pcap-dnsproxy/files/pcap-dnsproxy.init
--- a/package/external/chengr28/pcap-dnsproxy/files/pcap-dnsproxy.init
+++ b/package/external/chengr28/pcap-dnsproxy/files/pcap-dnsproxy.init
@@ -15,6 +15,7 @@ SERVICE_DAEMONIZE=1
 
 PROG=/usr/sbin/Pcap_DNSProxy
 CONFDIR=/etc/pcap-dnsproxy
+HOTPLUGFILE=/tmp/pcap-dnsproxy.hotplug
 ERRLOG=$CONFDIR/Error.log
 
 config_load "pcap-dnsproxy"
@@ -26,7 +27,27 @@ parse_pcap_dnsproxy()
 
 config_foreach parse_pcap_dnsproxy 'pcap-dnsproxy'
 
+boot() {
+	# wait a given time (default 10 seconds) before startup
+	# to wait for interfaces to come up / not using hotplug events during boot
+	_start() {
+		[ $1 -gt 0 ] && {
+			logger -p daemon.info -t "pcap-dnsproxy[]" "Scheduled startup in $1 seconds"
+			sleep $1
+		}
+		start
+	}
 
+	local _DELAY
+	_DELAY=$(uci_get "pcap-dnsproxy" "system" "boot_delay" "10")
+	_start $_DELAY &
+	return 0
+}
+
+shutdown() {
+	rm -f $HOTPLUGFILE
+	stop
+}
 
 start() {
 	[ "1" = "$ENABLED" -o "on" = "$ENABLED" -o "true" = "$ENABLED" ] && {
@@ -40,14 +61,21 @@ start() {
 		}
 		# do NOT use daemon code inside pcap-dnsproxy, use start-stop-daemon instead
 		service_start $PROG -c $CONFDIR --disable-daemon
+		# create hotplug mark, it will update the last-modified date if the file exists
+		touch $HOTPLUGFILE
 		local RESULT=$?
 		# wait to check error log file
 		sleep 1s
-		[ -f "$ERRLOG" ] && echo "WARNING: ${ERRLOG##*/} exists, check its content and other config files in ${CONFDIR}" || echo "Hooray! ${ERRLOG##*/} not found"
+		[ -f "$ERRLOG" ] \
+			&& echo "WARNING: ${ERRLOG##*/} exists, check its content and other config files in ${CONFDIR}" \
+			|| echo "Hooray! ${ERRLOG##*/} not found"
 		[ $RESULT -eq 0 -a $(ps|grep ${PROG}|grep -v grep|wc -l) -ge 1 ] && {
+			local _PID=$(pidof ${PROG##*/})
 			echo "Pcap_DNSProxy started successfully"
+			logger -p daemon.notice -t "Pcap_DNSProxy[$_PID]" "Started successfully"
 		} || {
 			echo "Pcap_DNSProxy failed to start"
+			logger -p daemon.warn -t "Pcap_DNSProxy[]" "Failed to start"
 			exit 1
 		}
 	} || {
@@ -59,14 +87,17 @@ stop() {
 	# If you can NOT terminate Pcap_DNSProxy, try 'killall' instead.
 	# e.g. killall -SIGTERM Pcap_DNSProxy
 	[ $(ps|grep ${PROG}|grep -v grep|wc -l) -ge 1 ] && {
+		local _PID=$(pidof ${PROG##*/})
 		service_stop $PROG
 		local RESULT=$?
 		sleep 1s
 		[ $RESULT -eq 0 -a $(ps|grep ${PROG}|grep -v grep|wc -l) -eq 0 ] && {
 			echo "Pcap_DNSProxy terminated successfully"
+			logger -p daemon.notice -t "Pcap_DNSProxy[$_PID]" "Shutdown successfully"
 			rm -rf "/tmp/pcap_dnsproxy_fifo"
 		} || {
 			echo "Failed to terminate Pcap_DNSProxy"
+			logger -p daemon.warn -t "Pcap_DNSProxy[$_PID]" "Failed to terminate"
 			echo "Retry or use 'killall -SIG{TERM,KILL} Pcap_DNSProxy' instead"
 		}
 	} || {
@@ -82,7 +113,9 @@ restart() {
 
 flush() {
 	[ $(ps|grep ${PROG}|grep -v grep|wc -l) -ge 1 ] && {
+		local _PID=$(pidof ${PROG##*/})
 		$PROG --flush-dns
+		logger -p daemon.notice -t "Pcap_DNSProxy[$_PID]" "Flush message sent"
 	} || {
 		echo "Pcap_DNSProxy is not running, I can NOT flush DNS cache for you."
 		exit 1
@@ -94,5 +127,7 @@ libver() {
 }
 
 status() {
-	[ $(ps|grep ${PROG}|grep -v grep|wc -l) -ge 1 ] && echo "Pcap_DNSProxy is running, PID is $(pidof ${PROG##*/})" || echo "Pcap_DNSProxy is NOT running"
+	[ $(ps|grep ${PROG}|grep -v grep|wc -l) -ge 1 ] \
+		&& echo "Pcap_DNSProxy is running, PID is $(pidof ${PROG##*/})" \
+		|| echo "Pcap_DNSProxy is NOT running"
 }
